// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TermProjectV1.Models;

namespace TermProjectV1.Migrations
{
    [DbContext(typeof(TrackerContext))]
    partial class TrackerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TermProjectV1.Models.Details", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("MemberID")
                        .HasColumnType("int");

                    b.Property<int>("age")
                        .HasColumnType("int");

                    b.Property<DateTime>("detailDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("MemberID");

                    b.ToTable("Statistics");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            MemberID = 1,
                            age = 34,
                            detailDate = new DateTime(2020, 12, 5, 16, 36, 19, 389, DateTimeKind.Local).AddTicks(2129)
                        },
                        new
                        {
                            ID = 2,
                            MemberID = 2,
                            age = 31,
                            detailDate = new DateTime(2020, 12, 5, 16, 36, 19, 392, DateTimeKind.Local).AddTicks(2131)
                        },
                        new
                        {
                            ID = 3,
                            MemberID = 3,
                            age = 37,
                            detailDate = new DateTime(2020, 12, 5, 16, 36, 19, 392, DateTimeKind.Local).AddTicks(2131)
                        });
                });

            modelBuilder.Entity("TermProjectV1.Models.Member", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("address")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("cell")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("city")
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnName("Member Full Name")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("state")
                        .HasColumnType("nvarchar(2)")
                        .HasMaxLength(2);

                    b.Property<string>("zip")
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.HasKey("ID");

                    b.ToTable("Membership");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            LastName = "Largent",
                            name = "Tim"
                        },
                        new
                        {
                            ID = 2,
                            LastName = "Lehr",
                            email = "mlehr@mail.com",
                            name = "Max"
                        },
                        new
                        {
                            ID = 3,
                            LastName = "Macki",
                            name = "Brett"
                        });
                });

            modelBuilder.Entity("TermProjectV1.Models.MemberReference", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("MemberID")
                        .HasColumnType("int");

                    b.Property<int>("ReferenceID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("MemberID");

                    b.HasIndex("ReferenceID");

                    b.ToTable("MemberReference");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            MemberID = 1,
                            ReferenceID = 1
                        },
                        new
                        {
                            ID = 2,
                            MemberID = 2,
                            ReferenceID = 2
                        },
                        new
                        {
                            ID = 3,
                            MemberID = 3,
                            ReferenceID = 3
                        });
                });

            modelBuilder.Entity("TermProjectV1.Models.Reference", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.Property<int>("ReferenceId")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("References");

                    b.HasData(
                        new
                        {
                            ID = 2,
                            LastName = "Macki",
                            Name = "Brett",
                            ReferenceId = 1
                        },
                        new
                        {
                            ID = 3,
                            LastName = "Largent",
                            Name = "Tim",
                            ReferenceId = 2
                        },
                        new
                        {
                            ID = 1,
                            LastName = "Lehr",
                            Name = "Max ",
                            ReferenceId = 3
                        });
                });

            modelBuilder.Entity("TermProjectV1.Models.Details", b =>
                {
                    b.HasOne("TermProjectV1.Models.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TermProjectV1.Models.MemberReference", b =>
                {
                    b.HasOne("TermProjectV1.Models.Member", "Member")
                        .WithMany("References")
                        .HasForeignKey("MemberID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TermProjectV1.Models.Reference", "Reference")
                        .WithMany("Member")
                        .HasForeignKey("ReferenceID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
